from python:3.8


workdir /app

COPY    requirements.txt /app/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app  



CMD ["Uvicorn", "main:app", "--host", "0.0.0.0", "--port", "'80"]